version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    ports: ['9200:9200']
    networks: ['ticket-search']

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.0
    ports: ['5601:5601']
    networks: ['ticket-search']
    depends_on: ['elasticsearch']

  mongo:
    image: mongo
    ports: ['27017:27017']
    networks: ['ticket-search']

#  logstash:
#      image: docker.elastic.co/logstash/logstash:6.1.0
#      networks: ['stack']
#      depends_on: ['elasticsearch']

networks: {ticket-search: {}}

#sudo sysctl -w vm.max_map_count=262144
#docker-compose -f docker-compose.yml up