logging:
  config: classpath:logback-local.xml

custom:
  rest:
    connection:
      connection-request-timeout: 10000
      connect-timeout: 10000
      read-timeout: 10000

spring:
  data:
    mongodb:
      database: "wizz"

search:
  threads: 20 # 0 to unlimited
#  repeatInterval: 3600000 # 1 hour
#  initialDelay: 3600000
#  cronScheadule: "0 0 0,6,12,18 * * *" # every day at 0:00 6:00 12:00 18:00
  cronScheadule: "0 10 22 * * *"
  days: 5
  whitelist:
    cities:
      enabled: true
      iatas:
      - BUD
      - LTN
    connections:
      enabled: true
      iatas:
      - BUD
      - LTN