logging:
  config: classpath:logback-local.xml

custom:
  rest:
    connection:
      connection-request-timeout: 10000
      connect-timeout: 10000
      read-timeout: 10000

spring:
  data:
    mongodb:
      database: "wizz"

search:
  threads: 10 # 0 to unlimited
  repeatInterval: 3600000 # 1 hour
  initialDelay: 3600000
  days: 2
  whitelist:
    enabled: false
    iatas:
      - BUD
      - LTN